import { useEffect, useMemo, useRef, useState } from 'react'
import { GitBranch, GraduationCap, TerminalSquare, Network, RotateCcw, Lightbulb, ChevronRight, Check, Download, Upload, Box, CircleDot, X } from 'lucide-react'
import { createState, execute } from './gitEngine'
import { lessons } from './lessons'
import type { GitState } from './types'

type Line={kind:'command'|'output'|'explain';text:string}
const STORAGE='git-playground-state-v1'
const setupLesson=(i:number)=>lessons[i].setup.reduce((s,c)=>execute(c,s).state,createState())
const commands=['git status','git add .','git commit -m "message"','git branch','git switch','git merge','git log --oneline --all --graph --decorate','git cherry-pick','git rebase','git reset --soft HEAD~1','touch','write','echo "Hello" > README.md','append','cat','ls']

export function App(){
 const [started,setStarted]=useState(false),[mode,setMode]=useState<'lesson'|'sandbox'>('lesson'),[lesson,setLesson]=useState(0),[hint,setHint]=useState(0),[novice,setNovice]=useState(true),[tab,setTab]=useState<'task'|'terminal'|'visual'>('terminal')
 const [verified,setVerified]=useState(false),[verifyMessage,setVerifyMessage]=useState('')
 const [state,setState]=useState<GitState>(()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||setupLesson(0)}catch{return setupLesson(0)}})
 const [lines,setLines]=useState<Line[]>([{kind:'output',text:'Git Playground ready. 输入 git status 开始。'}]),[input,setInput]=useState(''),[historyIndex,setHistoryIndex]=useState(-1),[selected,setSelected]=useState<string|null>(null)
 const scrollRef=useRef<HTMLDivElement>(null); useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(state)),[state]); useEffect(()=>scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight}),[lines]); useEffect(()=>{document.querySelectorAll<HTMLButtonElement>('.lesson-list button').forEach(button=>{button.disabled=false})})
 const complete=mode==='lesson'&&lessons[lesson].check(state)
 const run=(raw=input)=>{const cmd=raw.trim();if(!cmd)return;const r=execute(cmd,state);setState(r.state);setLines(old=>r.clear?[]:[...old,{kind:'command',text:`user@git-playground ${state.currentBranch} % ${cmd}`},...r.output.map(text=>({kind:'output' as const,text})),...(novice&&r.explanation?[{kind:'explain' as const,text:r.explanation}]:[])]);setInput('');setHistoryIndex(-1)}
 const reset=(index=lesson)=>{const s=mode==='lesson'?setupLesson(index):createState();setState(s);setLines([{kind:'output',text:mode==='lesson'?`关卡 ${index+1} 已就绪。`:'Sandbox 已重置。'}]);setHint(0);setVerified(false);setVerifyMessage('')}
 const chooseLesson=(i:number)=>{const next=setupLesson(i);next.remotes=structuredClone(state.remotes);setLesson(i);setMode('lesson');setState(next);setLines([{kind:'output',text:`关卡 ${i+1} · ${lessons[i].title}`},...(Object.keys(next.remotes).length?[{kind:'explain' as const,text:'已保留上一关的远程仓库连接。'}]:[])]);setHint(0);setVerified(false);setVerifyMessage('');setTab('terminal')}
 const verifyLesson=()=>{if(complete){setVerified(true);setVerifyMessage('验证通过！本关目标已完成，可以进入下一关。')}else{setVerified(false);if(lesson===0){const committed=state.head?state.commits[state.head]?.filesSnapshot['README.md']:undefined;if(committed===undefined)setVerifyMessage('尚未在提交中找到 README.md。请创建文件、写入内容、add，然后 commit。');else if(committed.length===0)setVerifyMessage('README.md 已经提交，但文件还是空的。请先用 write README.md "Hello Git" 写入内容，再 add 和 commit。');else setVerifyMessage('README.md 已有内容，但当前提交状态还未满足要求，请重新 add 并 commit。')}else setVerifyMessage('还没有完成目标。请检查当前分支、文件状态和提交历史，再试一次。')}}
 const key=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Enter')run();if(e.key==='ArrowUp'){e.preventDefault();const i=Math.min(state.commandHistory.length-1,historyIndex+1);setHistoryIndex(i);setInput(state.commandHistory[state.commandHistory.length-1-i]||'')}if(e.key==='ArrowDown'){e.preventDefault();const i=Math.max(-1,historyIndex-1);setHistoryIndex(i);setInput(i<0?'':state.commandHistory[state.commandHistory.length-1-i]||'')}if(e.key==='Tab'){e.preventDefault();const found=commands.find(c=>c.startsWith(input));if(found)setInput(found)}}
 const exportJson=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='git-playground.json';a.click();URL.revokeObjectURL(a.href)}
 const importJson=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;f.text().then(x=>{try{setState(JSON.parse(x));setLines(l=>[...l,{kind:'output',text:'Repository state imported.'}])}catch{setLines(l=>[...l,{kind:'output',text:'Invalid JSON file.'}])}})}
 if(!started)return <Landing onStart={()=>setStarted(true)} onSandbox={()=>{setStarted(true);setMode('sandbox');setState(createState())}}/>
 return <div className="app-shell">
  <header><div className="brand"><span className="brand-mark"><GitBranch size={18}/></span><b>Git Playground</b><span className="mode-chip">{mode==='lesson'?'闯关模式':'Sandbox'}</span></div><div className="header-actions"><button className="ghost" onClick={()=>{setMode(mode==='lesson'?'sandbox':'lesson');reset()}}>{mode==='lesson'?'自由练习':'返回关卡'}</button><label className="toggle"><input type="checkbox" checked={novice} onChange={e=>setNovice(e.target.checked)}/><span/>新手模式</label></div></header>
  <nav className="mobile-tabs"><button className={tab==='task'?'active':''} onClick={()=>setTab('task')}><GraduationCap/>任务</button><button className={tab==='terminal'?'active':''} onClick={()=>setTab('terminal')}><TerminalSquare/>终端</button><button className={tab==='visual'?'active':''} onClick={()=>setTab('visual')}><Network/>可视化</button></nav>
  <main>
   <aside className={`tasks ${tab==='task'?'mobile-active':''}`}><div className="panel-heading"><span>{mode==='lesson'?'LEARNING PATH':'SANDBOX'}</span>{mode==='lesson'&&<b>{lesson+1} / {lessons.length}</b>}</div>
    {mode==='lesson'?<><div className="progress"><i style={{width:`${((lesson+(verified?1:0))/lessons.length)*100}%`}}/></div><div className="lesson-copy"><span className="eyebrow">CHALLENGE {String(lesson+1).padStart(2,'0')}</span><h2>{lessons[lesson].title}</h2><p>{lessons[lesson].goal}</p>{verifyMessage&&<div className={verified?'success':'validation-error'}>{verified?<Check/>:<CircleDot/>}{verifyMessage}</div>}{hint>0&&<div className="hint"><Lightbulb/><p>{lessons[lesson].hints[hint-1]}</p></div>}<button className="verify" onClick={verifyLesson}><Check/>验证任务</button><div className="task-buttons"><button onClick={()=>setHint(Math.min(2,hint+1))}><Lightbulb/>提示 {hint}/2</button><button onClick={()=>reset()}><RotateCcw/>重置</button></div>{verified&&lesson<lessons.length-1&&<button className="next" onClick={()=>chooseLesson(lesson+1)}>下一关 <ChevronRight/></button>}</div><div className="lesson-list">{lessons.map((l,i)=><button key={l.title} className={i===lesson?'selected':''} onClick={()=>chooseLesson(i)} disabled={i>lesson+1}><span>{i<lesson?<Check/>:i+1}</span><p><b>{l.title}</b><small>{i===lesson?'正在进行':i<lesson?'已练习':'未开始'}</small></p></button>)}</div></>:<div className="lesson-copy"><span className="eyebrow">FREE PRACTICE</span><h2>自由实验</h2><p>不设目标，自由组合文件、分支和提交。状态会自动保存在本机。</p><div className="sandbox-actions"><button onClick={exportJson}><Download/>导出 JSON</button><label><Upload/>导入 JSON<input type="file" accept="application/json" onChange={importJson}/></label><button onClick={()=>reset()}><RotateCcw/>重置仓库</button></div></div>}
   </aside>
   <section className={`terminal-panel ${tab==='terminal'?'mobile-active':''}`}><div className="terminal-title"><div className="traffic"><i/><i/><i/></div><span><TerminalSquare/> terminal — git-playground</span><small>zsh</small></div>{novice&&<div className="available"><span>可用</span>{commands.slice(0,7).map(c=><button key={c} onClick={()=>setInput(c)}>{c}</button>)}</div>}<div className="terminal-body" ref={scrollRef} onClick={()=>document.getElementById('command-input')?.focus()}>{lines.map((l,i)=><div key={i} className={`line ${l.kind}`}>{l.kind==='explain'&&<span>↳ </span>}{l.text||' '}</div>)}<div className="prompt"><span>user@git-playground</span> <b>{state.currentBranch}</b> % <input id="command-input" autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={key} spellCheck={false} aria-label="Git command"/></div></div><div className="terminal-foot"><span><i/>模拟环境 · 不会执行真实 Shell</span><span>↑↓ 历史 · Tab 补全 · clear 清屏</span></div></section>
   <aside className={`visual ${tab==='visual'?'mobile-active':''}`}><StateView state={state} selected={selected} setSelected={setSelected} novice={novice}/></aside>
  </main>{selected&&state.commits[selected]&&<CommitModal state={state} id={selected} close={()=>setSelected(null)}/>}</div>
}
function Landing({onStart,onSandbox}:{onStart:()=>void;onSandbox:()=>void}){return <div className="landing"><div className="noise"/><nav><div className="brand"><span className="brand-mark"><GitBranch size={18}/></span><b>Git Playground</b></div><span>模拟 · 可视化 · 闯关</span></nav><div className="hero"><span className="hero-label"><CircleDot/> INTERACTIVE GIT LAB</span><h1>不要只背 Git 命令，<br/><em>亲手把分支玩明白。</em></h1><p>在安全的模拟终端中练习，用实时提交图看懂每一次 branch、merge 与 rebase。</p><div><button className="primary" onClick={onStart}>开始闯关 <ChevronRight/></button><button className="secondary" onClick={onSandbox}>自由练习</button></div></div><div className="preview-card"><div className="mini-terminal"><div><i/><i/><i/></div><code><span>main %</span> git switch -c feature<br/><b>Switched to a new branch 'feature'</b><br/><span>feature %</span> git commit -m "new idea"<br/><b>[feature a83fc1d] new idea</b></code></div><div className="mini-graph"><span className="pill">HEAD → feature</span><div className="graph-row"><i className="node purple"/><b>a83fc1d</b><span>new idea</span></div><div className="graph-row"><i className="line-v"/><i className="node green"/><b>4c129be</b><span>initial commit</span></div></div></div><footer>12 个循序渐进的练习 · 数据只保存在你的浏览器</footer></div>}
function StateView({state,selected,setSelected,novice}:{state:GitState;selected:string|null;setSelected:(x:string)=>void;novice:boolean}){const commits=useMemo(()=>{const seen=new Set<string>(),out:string[]=[];const walk=(id:string|null)=>{if(!id||seen.has(id))return;seen.add(id);out.push(id);state.commits[id]?.parentIds.forEach(walk)};Object.values(state.branches).forEach(b=>walk(b.commitId));return out.sort((a,b)=>state.commits[b].createdAt-state.commits[a].createdAt)},[state]);const working=Object.values(state.files).filter(f=>!['clean','staged'].includes(f.status)),staged=Object.values(state.files).filter(f=>f.status==='staged');return <><div className="viz-section"><h3>Working Directory <span>{working.length}</span></h3>{working.length?working.map(f=><div className="file" key={f.name}><Box/><b>{f.name}</b><em className={f.status}>{f.status}</em></div>):<Empty text="工作区干净"/>}</div><div className="viz-section"><h3>Staging Area <span>{staged.length}</span></h3>{staged.length?staged.map(f=><div className="file" key={f.name}><Box/><b>{f.name}</b><em className="staged">staged</em></div>):<Empty text="暂无暂存改动"/>}</div><div className="viz-section repo"><h3>Local Repository <span>{commits.length}</span></h3><div className="branch-tags">{Object.values(state.branches).map((b,i)=><span key={b.name} title={novice?`${b.name} 指向 ${b.commitId||'空提交'}`:undefined} className={b.name===state.currentBranch?'current':''} style={{'--h':`${190+i*48}`} as React.CSSProperties}>{b.name===state.currentBranch&&<b>HEAD → </b>}{b.name}</span>)}</div>{commits.length?<div className="commit-graph">{commits.map((id,i)=>{const c=state.commits[id],labels=Object.values(state.branches).filter(b=>b.commitId===id);return <button key={id} className={selected===id?'selected':''} onClick={()=>novice&&setSelected(id)}><span className="rail">{i<commits.length-1&&<i/>}<b className={id===state.head?'head':''}/>{c.parentIds.length>1&&<em/>}</span><span className="commit-copy"><code>{id}</code><strong>{c.message}</strong><small>{labels.map(x=>x.name).join(' · ')||new Date(c.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</small></span></button>})}</div>:<Empty text="还没有 commit"/>}</div><div className="viz-section remote"><h3>Remote Repository</h3>{state.remotes.origin?<><div className="remote-row"><span>origin/{state.currentBranch}</span><code>{state.remotes.origin.branches[state.currentBranch]||'—'}</code></div><small>{state.remotes.origin.upstream?'已设置 upstream':'尚未设置 upstream'}</small></>:<Empty text="git remote add origin URL"/>}</div></>}
function Empty({text}:{text:string}){return <div className="empty"><span>—</span>{text}</div>}
function CommitModal({state,id,close}:{state:GitState;id:string;close:()=>void}){const c=state.commits[id],p=c.parentIds[0]?state.commits[c.parentIds[0]]?.filesSnapshot:{};const changes=Object.keys({...p,...c.filesSnapshot}).filter(k=>p[k]!==c.filesSnapshot[k]);return <div className="modal" onClick={close}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">COMMIT {id}</span><h2>{c.message}</h2><p>{c.parentIds.length} 个父提交 · {new Date(c.createdAt).toLocaleString('zh-CN')}</p><h3>本次修改</h3>{changes.length?changes.map(n=><div className="change" key={n}><b>{n}</b><pre>{c.filesSnapshot[n]??'(deleted)'}</pre></div>):<Empty text="没有文件变化"/>}</div></div>}
