import { describe, expect, it } from 'vitest'
import { createState, execute } from './gitEngine'
const run=(cmds:string[])=>cmds.reduce((s,c)=>execute(c,s).state,createState())
const base=()=>run(['git init','write a.txt "one"','git add .','git commit -m "base"'])
describe('Git engine',()=>{
 it('branch does not switch',()=>{const s=execute('git branch feature',base()).state;expect(s.currentBranch).toBe('main');expect(s.branches.feature.commitId).toBe(s.head)})
 it('checkout updates HEAD',()=>{let s=base();s=execute('git branch f',s).state;s=execute('git switch f',s).state;expect(s.currentBranch).toBe('f');expect(s.head).toBe(s.branches.f.commitId)})
 it('commit includes only staged files',()=>{let s=base();s=execute('write a.txt "two"',s).state;s=execute('write b.txt "new"',s).state;s=execute('git add a.txt',s).state;s=execute('git commit -m "only a"',s).state;expect(s.commits[s.head!].filesSnapshot).toEqual({'a.txt':'two'})})
 it('echo writes and appends file content',()=>{let s=createState();s=execute('echo "Hello" > README.md',s).state;expect(s.files['README.md'].workingContent).toBe('Hello');s=execute('echo "Git" >> README.md',s).state;expect(s.files['README.md'].workingContent).toBe('Hello\nGit')})
 it('cherry-pick creates new id',()=>{let s=base();s=execute('git switch -c f',s).state;s=execute('write a.txt "f"',s).state;s=execute('git add .',s).state;s=execute('git commit -m "f"',s).state;const old=s.head!;s=execute('git switch main',s).state;s=execute(`git cherry-pick ${old}`,s).state;expect(s.head).not.toBe(old);expect(s.commits[s.head!].message).toBe('f')})
 it('rebase rewrites commit id',()=>{let s=base();s=execute('git switch -c f',s).state;s=execute('touch f',s).state;s=execute('git add .',s).state;s=execute('git commit -m "f"',s).state;const old=s.head!;s=execute('git switch main',s).state;s=execute('touch m',s).state;s=execute('git add .',s).state;s=execute('git commit -m "m"',s).state;s=execute('git switch f',s).state;s=execute('git rebase main',s).state;expect(s.head).not.toBe(old)})
 it('fast-forward merge moves pointer',()=>{let s=base();s=execute('git switch -c f',s).state;s=execute('touch f',s).state;s=execute('git add .',s).state;s=execute('git commit -m "f"',s).state;const tip=s.head;s=execute('git switch main',s).state;s=execute('git merge f',s).state;expect(s.head).toBe(tip)})
 it('normal merge has two parents',()=>{let s=base();s=execute('git switch -c f',s).state;s=execute('touch f',s).state;s=execute('git add .',s).state;s=execute('git commit -m "f"',s).state;s=execute('git switch main',s).state;s=execute('touch m',s).state;s=execute('git add .',s).state;s=execute('git commit -m "m"',s).state;s=execute('git merge f',s).state;expect(s.commits[s.head!].parentIds).toHaveLength(2)})
 it('reset modes preserve correct areas',()=>{for(const mode of ['soft','mixed','hard']){let s=base();s=execute('write a.txt "two"',s).state;s=execute('git add .',s).state;s=execute('git commit -m "two"',s).state;s=execute(`git reset --${mode} HEAD~1`,s).state;expect(s.files['a.txt'].workingContent).toBe(mode==='hard'?'one':'two');expect(s.files['a.txt'].status).toBe(mode==='soft'?'staged':mode==='hard'?'clean':'modified')}})
})
