import type { GitState } from './types'

export type Lesson = { title: string; goal: string; hints: [string,string]; setup: string[]; check: (s:GitState)=>boolean }
const branchHas = (s:GitState,n:string) => !!s.branches[n]?.commitId
export const lessons: Lesson[] = [
 {title:'第一次提交',goal:'创建 README.md，写入内容并完成第一次提交。',hints:['先创建文件，再想想 Git 提交前的中间区域。','touch README.md → write README.md "Hello Git" → git add README.md → git commit -m "first commit"'],setup:['git init'],check:s=>Object.keys(s.commits).length>=1&&!!s.commits[s.head!]?.filesSnapshot['README.md']},
 {title:'查看三种状态',goal:'依次制造 untracked、staged 和 modified 状态，并用 status 观察。',hints:['同一个文件在 add 前后、再次修改后，会出现三种状态。','touch app.js → git status → git add app.js → write app.js "v1" → git status'],setup:['git init'],check:s=>s.commandHistory.filter(x=>x==='git status').length>=2},
 {title:'创建与切换分支',goal:'创建 s1 分支，然后切换到它。',hints:['创建分支不会自动切换。','git branch s1 → git switch s1'],setup:['git init','touch base.txt','git add .','git commit -m "base"'],check:s=>s.currentBranch==='s1'&&!!s.branches.s1},
 {title:'在 s1 开发',goal:'在 s1 创建提交，并确保 main 仍停留在原处。',hints:['先切换分支，再改文件并提交。','git switch -c s1 → write app.js "s1 work" → git add . → git commit -m "work on s1"'],setup:['git init','touch app.js','git add .','git commit -m "base"'],check:s=>branchHas(s,'s1')&&s.branches.s1.commitId!==s.branches.main.commitId},
 {title:'合并 feature',goal:'把 feature 的开发成果合并回 main。',hints:['合并发生在接收改动的分支上。','git switch feature → write app.js "feature" → git add . → git commit -m "feature" → git switch main → git merge feature'],setup:['git init','touch app.js','git add .','git commit -m "base"','git branch feature'],check:s=>s.currentBranch==='main'&&s.branches.main.commitId===s.branches.feature.commitId},
 {title:'Fast-forward',goal:'完成一次不产生 merge commit 的快进合并。',hints:['main 不要在分叉后产生新提交。','git switch feature → write f.txt "done" → git add . → git commit -m "feature" → git switch main → git merge feature'],setup:['git init','touch base','git add .','git commit -m "base"','git branch feature'],check:s=>s.currentBranch==='main'&&s.branches.main.commitId===s.branches.feature.commitId},
 {title:'普通 Merge',goal:'让 main 与 feature 各自前进，再生成双亲 merge commit。',hints:['两个分支各自提交不同文件，最后在 main 合并。','git switch feature → touch feature.txt → git add . → git commit -m "feature" → git switch main → touch main.txt → git add . → git commit -m "main" → git merge feature'],setup:['git init','touch base','git add .','git commit -m "base"','git branch feature'],check:s=>!!s.head&&s.commits[s.head]?.parentIds.length===2},
 {title:'Cherry-pick',goal:'在 s2 上复制 s1 的独有提交。',hints:['先在图中找到 s1 最新提交的 ID，再切换到 s2。','git switch s2 → git cherry-pick <s1 的提交 ID>'],setup:['git init','write app.js "base"','git add .','git commit -m "base"','git branch s2','git switch -c s1','write app.js "s1 work"','git add .','git commit -m "develop on s1"'],check:s=>branchHas(s,'s2')&&s.branches.s2.commitId!==s.commits[s.branches.s2.commitId!]?.parentIds[0]},
 {title:'Rebase 整理历史',goal:'把 feature 的独有提交变基到最新 main。',hints:['在被整理的 feature 分支上执行 rebase。','git switch feature → git rebase main'],setup:['git init','touch base','git add .','git commit -m "base"','git switch -c feature','touch feature','git add .','git commit -m "feature"','git switch main','touch main','git add .','git commit -m "main"'],check:s=>s.commandHistory.includes('git rebase main')},
 {title:'撤销 Add',goal:'把 note.txt 移出暂存区，但保留工作区内容。',hints:['restore 有一个只针对 staging area 的选项。','git restore --staged note.txt'],setup:['git init','write note.txt "draft"','git add note.txt'],check:s=>s.commandHistory.includes('git restore --staged note.txt')&&s.files['note.txt']?.status!=='staged'},
 {title:'Reset 三种模式',goal:'尝试 soft、mixed 或 hard reset，观察三区域差异。',hints:['三种模式移动 HEAD 的方式相同，保留改动的位置不同。','提交一次改动后执行 git reset --soft HEAD~1（也可换 mixed / hard）'],setup:['git init','write a.txt "v1"','git add .','git commit -m "v1"','write a.txt "v2"','git add .','git commit -m "v2"'],check:s=>s.commandHistory.some(x=>x.startsWith('git reset --'))},
 {title:'解决冲突',goal:'合并产生冲突后，解决 app.js 并完成提交。',hints:['先 merge，再 resolve 冲突文件，add 并 commit。','git merge feature → resolve app.js "最终内容" → git add app.js → git commit -m "resolve conflict"'],setup:['git init','write app.js "base"','git add .','git commit -m "base"','git switch -c feature','write app.js "feature"','git add .','git commit -m "feature"','git switch main','write app.js "main"','git add .','git commit -m "main"'],check:s=>s.commandHistory.some(x=>x.startsWith('resolve '))&&s.conflictFiles.length===0&&!!s.head},
]
